[context_destroyed.py]
  [test_new_user_context[window\]]
    expected: FAIL
