[simulate_gatt_disconnection.py]
  [test_simulate_gatt_disconnection]
    expected: FAIL
