[invalid.py]
  [test_params_context_invalid_type[False\]]
    expected: ERROR

  [test_params_context_invalid_type[42\]]
    expected: ERROR

  [test_params_context_invalid_type[value3\]]
    expected: ERROR

  [test_params_context_invalid_type[value4\]]
    expected: ERROR

  [test_params_context_invalid_value[\]]
    expected: ERROR

  [test_params_context_invalid_value[somestring\]]
    expected: ERROR

  [test_params_accept_invalid_type[foo\]]
    expected: ERROR

  [test_params_accept_invalid_type[42\]]
    expected: ERROR

  [test_params_accept_invalid_type[value2\]]
    expected: ERROR

  [test_params_accept_invalid_type[value3\]]
    expected: ERROR

  [test_params_user_text_invalid_type[False\]]
    expected: ERROR

  [test_params_user_text_invalid_type[42\]]
    expected: ERROR

  [test_params_user_text_invalid_type[value2\]]
    expected: ERROR

  [test_params_user_text_invalid_type[value3\]]
    expected: ERROR

  [test_no_alert]
    expected: ERROR
