[realm_destroyed.py]
  [test_dedicated_worker]
    expected: FAIL
