[invalid.py]
  [test_params_proxy_socks_proxy_invalid_type[42\]]
    expected: FAIL

  [test_params_proxy_socks_proxy_invalid_type[True\]]
    expected: FAIL

  [test_params_proxy_socks_proxy_invalid_type[value3\]]
    expected: FAIL
